### ISSUE TITLE
File deleted bug

### ISSUE THREAD

**Issue by Nintendocustom** [RISE-Project-STI2D/gdrive2discord#1]
Every time someone opens a file, the bot writes that the file has been deleted.

**Comment by maxerbox** [comment]
I'm gonna check it out, I've recently allowed public folder watching in 0e388c6, that's probably the cause

**Comment by maxerbox** [comment]
Is it still happening ?

**Comment by afadfafsa** [comment]
Sometimes

**Comment by Nintendocustom** [comment]
Now it's better, but sometimes the error appears.
