### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by thealexparadox** [RISE-Project-STI2D/gdrive2discord#3]
To replicate the issue:

Authorize access to Google Drive changes stream GO

I click the GO

I attempt to sign in and get that error message.

![Capture](https://user-images.githubusercontent.com/21365310/62830041-752fb600-bbd5-11e9-82f8-73af52168cd4.PNG)

**Comment by maxerbox** [comment]
I will check out what's happening with google

**Comment by maxerbox** [comment]
As the instance is not more maintened, I'm closing this
