### ISSUE TITLE
[ERROR] usage: .\gdrive2discord.exe <configuration_file>

### ISSUE THREAD

**Issue by NullBruce** [RISE-Project-STI2D/gdrive2discord#5]
whenever i try to `go run main.go` or `go build` i get this error: [**ERROR] usage:  .\gdrive2discord.exe <configuration_file> exit status 1**.

so obviously it has something to do with config, i wonder what did i miss.

![bot](https://user-images.githubusercontent.com/63065211/78361603-f6024e80-75b8-11ea-84dc-6600d171e8e9.PNG)

**Comment by Daniel-Mendes** [comment]
@NullBruce You need to specifiy the file to use: ```gdrive2discord configuration.json```
